# SQL - structured querry language

#### SQLite Datenbank im Termial aus den colorsurvey-Dateien erstellen:

sqlite3 mainsurvey.db < mainsurvey_sqldump.txt

---

# Fragen/Aufgaben:
## - Aufbau einer RGB-Karte mit entsprechenden Farbbegriffen
- ohne Daten der farbenblinden Menschen
- alle Daten
- nur Frauen
- nur Männer
## - wie gut/schlecht können farbenblinde Menschen Farben im Vergleich zu nicht farbenblinden Menschen einordnen?
## - Unterschied im Farbensehen zwischen Mann und Frau?

#### Zugriff aus python mit Hilfe von Pandas

In [1]:
import sqlite3 as sql
import pandas as pd
import numpy as np

Baue eine Verbindung zur meiner Datenbank auf:

In [2]:
conn = sql.connect('data/colorsurvey/mainsurvey.db')

### Die Daten aus der SQL mit Hilfe von Pandas auslesen

In [3]:
# Lese die Werte aus allen (*) Spalten der Tabelle 'answers' und gebe mir maximal 5 Ergebniszeilen zurück
pd.read_sql_query('SELECT * FROM answers LIMIT 5;', conn)

   id  user_id     datestamp    r    g    b     colorname
0   1        1  1.267419e+09   72  100  175   pastel blue
1   2        1  1.267419e+09  204  177  246  faint violet
2   3        1  1.267419e+09  182  226  245     baby blue
3   4        1  1.267419e+09  130   64  234        purple
4   5        2  1.267419e+09   75   49  234          blue

In [4]:
# Lese die Werte aus allen (*) Spalten der Tabelle 'users' und gebe mir maximal 5 Ergebniszeilen zurück
pd.read_sql_query('SELECT * FROM users LIMIT 10;', conn)

,id,user_key,datestamp,ip,language,monitor,temperature,gamma,colorblind,ychrom,samplecolors,spamprob
0,1,1irzBJF4C4MNNn5H3Ww7SFNRvqSUG,1.267419e+09,0.0.0.0,None,LCD,6500.0,2.2,0,1,blue/royal periwinkle,0.002088
1,2,1hW1tdQ5iCxFnIy4Xpc3ckh18ZDL,1.267419e+09,0.0.0.0,None,LCD,6500.0,NaN,0,1,pink/pale salmon,0.074577
2,3,1GI5SzNKh6ntR5mhD494MkZG0s4Zk1,1.267419e+09,0.0.0.0,None,LCD,NaN,NaN,0,1,green/light olive,0.016404
3,4,18l2GajPo4ptcw1YTXKRm1Xn8jEfNN,1.267419e+09,0.0.0.0,None,LCD,NaN,NaN,0,0,green/light olive,0.001562
4,5,1Qd1F6Oi9B4E6c7xInaDeqIRxmJevx1,1.267419e+09,0.0.0.0,None,LCD,6500.0,2.2,0,1,brown/raw umber,0.002381
5,6,1AbCsPkXYvMeAZ8WRSRZSYZdZk5TqT1,1.267419e+09,0.0.0.0,None,LCD,NaN,NaN,0,1,green/light olive,0.014400
6,7,1dbqNkYK7MlQaUkFadLRcggrwEhNf,1.267419e+09,0.0.0.0,None,CRT,9300.0,NaN,0,1,yellow/bright mustard,0.024112
7,8,1AbF4Jqo3aesG5pCBGIw1O691iCNB0,1.267419e+09,0.0.0.0,None,LCD,NaN,NaN,0,1,gray/charcoal,0.000716
8,9,1dpnCq0N63P8bPbmVxdLLnnW1rKCdQ,1.267419e+09,0.0.0.0,None,LCD,NaN,NaN,0,1,purple/bluish fuschia,0.009788
9,10,1bBpqR7DMb6EfAbZOuZO7vYkkLnz0,1.267419e+09,0.0.0.0,None,LCD,NaN,NaN,0,1,gray/charcoal,0.175683

In [5]:
# Lese die Werte aus den Spalten 'r', 'g', 'b' und 'colorname' der Tabelle 'answers' aus und gebe mir maximal 5 Ergebniszeilen zurück
pd.read_sql_query('SELECT r,g,b,colorname FROM answers LIMIT 10;', conn)

     r    g    b     colorname
0   72  100  175   pastel blue
1  204  177  246  faint violet
2  182  226  245     baby blue
3  130   64  234        purple
4   75   49  234          blue
5   76  215  249    light blue
6  111  145  122   olive green
7   88   70    1         brown
8  218   35  156          pink
9  154   42  159        purple

### Gruppieren von Daten

In [6]:
# Gruppiere die Daten aus 'answers' anhand der Einträge in colorname.
# Wähle nur die Eintrage welche die Buchstaben 'blue' enhalten aus (WHERE).
# Gebe den Eintrag 'colorname' aus und zähle (COUNT(*)) die Anzahl der Einträge pro Gruppe 
# und gebe diesen ebenfalls aus. Weise diesem Wert den Namen 'numer_entries' (AS) zu.
# Gebe nur die Gruppen aus die mehr als 100 Einträge (HAVING) haben aus
# Sortiere das Ergebnis nach der Anzahl der Einträge (ORDER BY) absteigend (DESC)
pd.read_sql_query(
    'SELECT ' +
        'colorname, ' +
        'COUNT(*) AS number_entries ' +
    'FROM answers ' +
    'WHERE colorname LIKE "%blue%" ' +
    'GROUP BY colorname ' +
    'HAVING number_entries > 100 ' +
    'ORDER BY number_entries DESC; '
    , conn)

                      colorname  number_entries
0                          blue          287938
1                    light blue           58119
2                      sky blue           34501
3                     dark blue           23439
4                    royal blue           15060
5                     navy blue           13596
6                   bright blue            8458
7                     pale blue            7049
8                     baby blue            6434
9                    blue-green            5523
10                   blue green            5106
11                    grey blue            3595
12                    deep blue            3157
13                    blue-grey            2955
14                   slate blue            2929
15                    blue grey            2872
16                     sea blue            2672
17             robin's egg blue            2504
18                   steel blue            2474
19                    grey-blue            2424
20                  blue-purple            2292
21                  medium blue            2244
22                   ocean blue            2125
23                    blue gray            1988
24              cornflower blue            1970
25                midnight blue            1958
26                purplish blue            1926
27                    blue-gray            1886
28                 greyish blue            1868
29                electric blue            1805
..                          ...             ...
163                   ugly blue             130
164               greenish-blue             129
165             light grey-blue             129
166                 petrol blue             129
167                       bluer             126
168                    off blue             125
169             pale blue-green             121
170                 stormy blue             119
171             dark green-blue             116
172           light blue-purple             116
173                 strong blue             116
174                   blue blue             115
175                  azure blue             114
176                    bluegray             113
177                 cloudy blue             112
178                purpley-blue             112
179  blue with a hint of purple             111
180                 boring blue             111
181                windows blue             111
182              dark blue-gray             109
183           really light blue             108
184                greyish-blue             107
185                  cloud blue             105
186                   cyan blue             105
187             dark green blue             105
188              dark grey-blue             105
189             light gray blue             104
190                another blue             101
191             aquamarine blue             101
192                intense blue             101

[193 rows x 2 columns]

### Daten aus verschiedenen Tabellen joinen

Möglichkeiten Einträge zweier Tabellen zusammenzuführen, funktioniert mittels den 'JOIN' Befehlen. Zwei oder mehr Tabellen werden auf (ON) einer Bedingung zusammengeführt.

'LEFT JOIN' (alle Datenreien der linken Tabelle sind im Ergebnis enthalten, auch wenn es keine Daten dazu in der rechten Tabelle gibt)

'RIGHT JOIN' (alle Datenreien der rechten Tabelle sind im Ergebnis enthalten, auch wenn es keine Daten dazu in der linken Tabelle gibt) 

'OUTER JOIN' (alle Datenreien beider Tabellen sind im Ergebnis enthalten)
'INNER JOIN' (nur die Datenreien zu denen es Daten in beiden Tabellen gibt sind enthalten)

In [7]:
df = pd.read_sql_query('SELECT * FROM answers INNER JOIN users ON users.id = answers.user_id;', conn)

In [8]:
df
# wofür steht:
# samplecolors, spamprob?

,id,user_id,datestamp,r,g,b,colorname,id,user_key,datestamp,ip,language,monitor,temperature,gamma,colorblind,ychrom,samplecolors,spamprob
0,1,1,1.267419e+09,72,100,175,pastel blue,1,1irzBJF4C4MNNn5H3Ww7SFNRvqSUG,1.267419e+09,0.0.0.0,None,LCD,6500.0,2.2,0.0,1.0,blue/royal periwinkle,0.002088
1,2,1,1.267419e+09,204,177,246,faint violet,1,1irzBJF4C4MNNn5H3Ww7SFNRvqSUG,1.267419e+09,0.0.0.0,None,LCD,6500.0,2.2,0.0,1.0,blue/royal periwinkle,0.002088
2,3,1,1.267419e+09,182,226,245,baby blue,1,1irzBJF4C4MNNn5H3Ww7SFNRvqSUG,1.267419e+09,0.0.0.0,None,LCD,6500.0,2.2,0.0,1.0,blue/royal periwinkle,0.002088
3,4,1,1.267419e+09,130,64,234,purple,1,1irzBJF4C4MNNn5H3Ww7SFNRvqSUG,1.267419e+09,0.0.0.0,None,LCD,6500.0,2.2,0.0,1.0,blue/royal periwinkle,0.002088
4,5,2,1.267419e+09,75,49,234,blue,2,1hW1tdQ5iCxFnIy4Xpc3ckh18ZDL,1.267419e+09,0.0.0.0,None,LCD,6500.0,NaN,0.0,1.0,pink/pale salmon,0.074577
5,6,2,1.267419e+09,76,215,249,light blue,2,1hW1tdQ5iCxFnIy4Xpc3ckh18ZDL,1.267419e+09,0.0.0.0,None,LCD,6500.0,NaN,0.0,1.0,pink/pale salmon,0.074577
6,7,2,1.267419e+09,111,145,122,olive green,2,1hW1tdQ5iCxFnIy4Xpc3ckh18ZDL,1.267419e+09,0.0.0.0,None,LCD,6500.0,NaN,0.0,1.0,pink/pale salmon,0.074577
7,8,2,1.267419e+09,88,70,1,brown,2,1hW1tdQ5iCxFnIy4Xpc3ckh18ZDL,1.267419e+09,0.0.0.0,None,LCD,6500.0,NaN,0.0,1.0,pink/pale salmon,0.074577
8,9,2,1.267419e+09,218,35,156,pink,2,1hW1tdQ5iCxFnIy4Xpc3ckh18ZDL,1.267419e+09,0.0.0.0,None,LCD,6500.0,NaN,0.0,1.0,pink/pale salmon,0.074577
9,10,4,1.267419e+09,154,42,159,purple,4,18l2GajPo4ptcw1YTXKRm1Xn8jEfNN,1.267419e+09,0.0.0.0,None,LCD,NaN,NaN,0.0,0.0,green/light olive,0.001562
10,11,2,1.267419e+09,179,67,229,purple,2,1hW1tdQ5iCxFnIy4Xpc3ckh18ZDL,1.267419e+09,0.0.0.0,None,LCD,6500.0,NaN,0.0,1.0,pink/pale salmon,0.074577
11,12,3,1.267419e+09,92,97,190,navy,3,1GI5SzNKh6ntR5mhD494MkZG0s4Zk1,1.267419e+09,0.0.0.0,None,LCD,NaN,NaN,0.0,1.0,green/light olive,0.016404
12,13,4,1.267419e+09,116,208,126,green,4,18l2GajPo4ptcw1YTXKRm1Xn8jEfNN,1.267419e+09,0.0.0.0,None,LCD,NaN,NaN,0.0,0.0,green/light olive,0.001562
13,14,2,1.267419e+09,9,2,21,black,2,1hW1tdQ5iCxFnIy4Xpc3ckh18ZDL,1.267419e+09,0.0.0.0,None,LCD,6500.0,NaN,0.0,1.0,pink/pale salmon,0.074577
14,15,2,1.267419e+09,69,255,41,green,2,1hW1tdQ5iCxFnIy4Xpc3ckh18ZDL,1.267419e+09,0.0.0.0,None,LCD,6500.0,NaN,0.0,1.0,pink/pale salmon,0.074577
15,16,4,1.267419e+09,27,34,98,navy blue,4,18l2GajPo4ptcw1YTXKRm1Xn8jEfNN,1.267419e+09,0.0.0.0,None,LCD,NaN,NaN,0.0,0.0,green/light olive,0.001562
16,17,2,1.267419e+09,41,201,234,blue,2,1hW1tdQ5iCxFnIy4Xpc3ckh18ZDL,1.267419e+09,0.0.0.0,None,LCD,6500.0,NaN,0.0,1.0,pink/pale salmon,0.074577
17,18,3,1.267419e+09,99,212,32,lime green,3,1GI5SzNKh6ntR5mhD494MkZG0s4Zk1,1.267419e+09,0.0.0.0,None,LCD,NaN,NaN,0.0,1.0,green/light olive,0.016404
18,19,2,1.267419e+09,160,89,66,red brown,2,1hW1tdQ5iCxFnIy4Xpc3ckh18ZDL,1.267419e+09,0.0.0.0,None,LCD,6500.0,NaN,0.0,1.0,pink/pale salmon,0.074577
19,20,2,1.267419e+09,204,117,64,orange,2,1hW1tdQ5iCxFnIy4Xpc3ckh18ZDL,1.267419e+09,0.0.0.0,None,LCD,6500.0,NaN,0.0,1.0,pink/pale salmon,0.074577
20,21,4,1.267419e+09,12,208,219,teal,4,18l2GajPo4ptcw1YTXKRm1Xn8jEfNN,1.267419e+09,0.0.0.0,None,LCD,NaN,NaN,0.0,0.0,green/light olive,0.001562
21,22,2,1.267419e+09,73,97,236,blue,2,1hW1tdQ5iCxFnIy4Xpc3ckh18ZDL,1.267419e+09,0.0.0.0,None,LCD,6500.0,NaN,0.0,1.0,pink/pale salmon,0.074577
22,23,4,1.267419e+09,131,79,90,aubergine,4,18l2GajPo4ptcw1YTXKRm1Xn8jEfNN,1.267419e+09,0.0.0.0,None,LCD,NaN,NaN,0.0,0.0,green/light olive,0.001562
23,24,3,1.267419e+09,209,202,95,dark tan,3,1GI5SzNKh6ntR5mhD494MkZG0s4Zk1,1.267419e+09,0.0.0.0,None,LCD,NaN,NaN,0.0,1.0,green/light olive,0.016404
24,25,4,1.267419e+09,77,147,83,moss green,4,18l2GajPo4ptcw1YTXKRm1Xn8jEfNN,1.267419e+09,0.0.0.0,None,LCD,NaN,NaN,0.0,0.0,green/light olive,0.001562
25,26,4,1.267419e+09,136,30,75,magenta,4,18l2GajPo4ptcw1YTXKRm1Xn8jEfNN,1.267419e+09,0.0.0.0,None,LCD,NaN,NaN,0.0,0.0,green/light olive,0.001562
26,27,4,1.267419e+09,33,115,229,blue,4,18l2GajPo4ptcw1YTXKRm1Xn8jEfNN,1.267419e+09,0.0.0.0,None,LCD,NaN,NaN,0.0,0.0,green/light olive,0.001562
27,28,5,1.267419e+09,232,171,51,goldenrod,5,1Qd1F6Oi9B4E6c7xInaDeqIRxmJevx1,1.267419e+09,0.0.0.0,None,LCD,6500.0,2.2,0.0,1.0,brown/raw umber,0.002381
28,29,3,1.267419e+09,99,46,219,purplish blue,3,1GI5SzNKh6ntR5mhD494MkZG0s4Zk1,1.267419e+09,0.0.0.0,None,LCD,NaN,NaN,0.0,1.0,green/light olive,0.016404
29,30,4,1.267419e+09,212,209,208,gray,4,18l2GajPo4ptcw1YTXKRm1Xn8jEfNN,1.267419e+09,0.0.0.0,None,LCD,NaN,NaN,0.0,0.0,green/light olive,0.001562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3408006,3408008,152393,1.270252e+09,185,89,32,rust,152393,1Fqn7aN8kB7oBHNaHyKX10UfKDScPx1,1.270252e+09,0.0.0.0,English,LCD,NaN,NaN,0.0,1.0,brown/raw umber,0.002724
3408007,3408009,152390,1.270252e+09,147,103,192,violet,152390,1spjZydDOLc9eUqQK7q5CmHXchOa1,1.270252e+09,0.0.0.0,Finnish,LCD,NaN,1.0,0.0,1.0,gray/charcoal,0.192718
3408008,3408010,152390,1.270252e+09,13,34,226,blue,152390,1spjZydDOLc9eUqQK7q5CmHXchOa1,1.270252e+09,0.0.0.0,Finnish,LCD,NaN,1.0,0.0,1.0,gray/charcoal,0.192718
3408009,3408011,152398,1.270252e+09,158,9,140,reddish purple,152398,1EuLfkp08hmsmJZgzlXrY3Rq5H7fB,1.270252e+09,0.0.0.0,English,LCD,NaN,NaN,0.0,1.0,gray/charcoal,0.002146
3408010,3408012,152393,1.270252e+09,143,143,240,sky blue,152393,1Fqn7aN8kB7oBHNaHyKX10UfKDScPx1,1.270252e+09,0.0.0.0,English,LCD,NaN,NaN,0.0,1.0,brown/raw umber,0.002724
3408011,3408013,152390,1.270252e+09,134,199,21,gren,152390,1spjZydDOLc9eUqQK7q5CmHXchOa1,1.270252e+09,0.0.0.0,Finnish,LCD,NaN,1.0,0.0,1.0,gray/charcoal,0.192718
3408012,3408014,152397,1.270252e+09,129,176,205,light teal,152397,1ThdC7uTuUaqeKW30bjJRsBut4ftq,1.270252e+09,0.0.0.0,Hebrew,LCD,NaN,NaN,0.0,1.0,red/dark russet,0.000707
3408013,3408015,152390,1.270252e+09,65,47,254,blue,152390,1spjZydDOLc9eUqQK7q5CmHXchOa1,1.270252e+09,0.0.0.0,Finnish,LCD,NaN,1.0,0.0,1.0,gray/charcoal,0.192718
3408014,3408016,152393,1.270252e+09,90,232,15,neon green,152393,1Fqn7aN8kB7oBHNaHyKX10UfKDScPx1,1.270252e+09,0.0.0.0,English,LCD,NaN,NaN,0.0,1.0,brown/raw umber,0.002724
3408015,3408017,152390,1.270252e+09,135,54,104,purple,152390,1spjZydDOLc9eUqQK7q5CmHXchOa1,1.270252e+09,0.0.0.0,Finnish,LCD,NaN,1.0,0.0,1.0,gray/charcoal,0.192718
3408016,3408018,152398,1.270252e+09,81,81,92,dark turqoise,152398,1EuLfkp08hmsmJZgzlXrY3Rq5H7fB,1.270252e+09,0.0.0.0,English,LCD,NaN,NaN,0.0,1.0,gray/charcoal,0.002146
3408017,3408019,152397,1.270252e+09,212,32,118,dark pink,152397,1ThdC7uTuUaqeKW30bjJRsBut4ftq,1.270252e+09,0.0.0.0,Hebrew,LCD,NaN,NaN,0.0,1.0,red/dark russet,0.000707
3408018,3408020,152390,1.270252e+09,123,139,69,green,152390,1spjZydDOLc9eUqQK7q5CmHXchOa1,1.270252e+09,0.0.0.0,Finnish,LCD,NaN,1.0,0.0,1.0,gray/charcoal,0.192718
3408019,3408021,152390,1.270252e+09,113,163,26,green,152390,1spjZydDOLc9eUqQK7q5CmHXchOa1,1.270252e+09,0.0.0.0,Finnish,LCD,NaN,1.0,0.0,1.0,gray/charcoal,0.192718
3408020,3408022,152398,1.270252e+09,83,90,44,dark olive drab,152398,1EuLfkp08hmsmJZgzlXrY3Rq5H7fB,1.270252e+09,0.0.0.0,English,LCD,NaN,NaN,0.0,1.0,gray/charcoal,0.002146
3408021,3408023,152400,1.270252e+09,56,163,14,green,152400,1UhyJIdsjPoPVCz54Z9jjb3UYdPVbj0,1.270252e+09,0.0.0.0,English,LCD,NaN,NaN,0.0,1.0,red/dark russet,0.000076
3408022,3408024,152390,1.270252e+09,218,118,214,violet,152390,1spjZydDOLc9eUqQK7q5CmHXchOa1,1.270252e+09,0.0.0.0,Finnish,LCD,NaN,1.0,0.0,1.0,gray/charcoal,0.192718
3408023,3408025,152390,1.270252e+09,19,121,3,green,152390,1spjZydDOLc9eUqQK7q5CmHXchOa1,1.270252e+09,0.0.0.0,Finnish,LCD,NaN,1.0,0.0,1.0,gray/charcoal,0.192718
3408024,3408026,152393,1.270252e+09,197,88,169,fuchsia,152393,1Fqn7aN8kB7oBHNaHyKX10UfKDScPx1,1.270252e+09,0.0.0.0,English,LCD,NaN,NaN,0.0,1.0,brown/raw umber,0.002724
3408025,3408027,152398,1.270252e+09,207,128,115,dark rose,152398,1EuLfkp08hmsmJZgzlXrY3Rq5H7fB,1.270252e+09,0.0.0.0,English,LCD,NaN,NaN,0.0,1.0,gray/charcoal,0.002146
3408026,3408028,152390,1.270252e+09,14,249,83,light green,152390,1spjZydDOLc9eUqQK7q5CmHXchOa1,1.270252e+09,0.0.0.0,Finnish,LCD,NaN,1.0,0.0,1.0,gray/charcoal,0.192718
3408027,3408029,152398,1.270252e+09,10,73,231,blue,152398,1EuLfkp08hmsmJZgzlXrY3Rq5H7fB,1.270252e+09,0.0.0.0,English,LCD,NaN,NaN,0.0,1.0,gray/charcoal,0.002146
3408028,3408030,152401,1.270252e+09,50,247,195,teel,152401,1MEUE3jFAZqLHCJoWuCF7Z3YQDqEQ0,1.270252e+09,0.0.0.0,English,LCD,NaN,NaN,0.0,1.0,orange/reddish ochre,0.073684
3408029,3408031,152393,1.270252e+09,210,58,201,light fuchsia,152393,1Fqn7aN8kB7oBHNaHyKX10UfKDScPx1,1.270252e+09,0.0.0.0,English,LCD,NaN,NaN,0.0,1.0,brown/raw umber,0.002724
3408030,3408032,152390,1.270252e+09,85,159,163,green,152390,1spjZydDOLc9eUqQK7q5CmHXchOa1,1.270252e+09,0.0.0.0,Finnish,LCD,NaN,1.0,0.0,1.0,gray/charcoal,0.192718
3408031,3408033,152401,1.270252e+09,31,79,57,dark teel,152401,1MEUE3jFAZqLHCJoWuCF7Z3YQDqEQ0,1.270252e+09,0.0.0.0,English,LCD,NaN,NaN,0.0,1.0,orange/reddish ochre,0.073684
3408032,3408034,152401,1.270252e+09,77,0,75,purple,152401,1MEUE3jFAZqLHCJoWuCF7Z3YQDqEQ0,1.270252e+09,0.0.0.0,English,LCD,NaN,NaN,0.0,1.0,orange/reddish ochre,0.073684
3408033,3408035,152390,1.270252e+09,5,18,55,dark blue,152390,1spjZydDOLc9eUqQK7q5CmHXchOa1,1.270252e+09,0.0.0.0,Finnish,LCD,NaN,1.0,0.0,1.0,gray/charcoal,0.192718
3408034,3408036,152398,1.270252e+09,179,28,183,light purple,152398,1EuLfkp08hmsmJZgzlXrY3Rq5H7fB,1.270252e+09,0.0.0.0,English,LCD,NaN,NaN,0.0,1.0,gray/charcoal,0.002146
3408035,3408037,152393,1.270252e+09,19,14,78,midnight blue,152393,1Fqn7aN8kB7oBHNaHyKX10UfKDScPx1,1.270252e+09,0.0.0.0,English,LCD,NaN,NaN,0.0,1.0,brown/raw umber,0.002724

### Spalten, die für mich keine nennenswerten Informationen enthalen:
- user_key, ip, samplecolors, spamprob
--> droppen dieser Spalten

In [9]:
df2 = df.drop(["user_key", "ip", "samplecolors", "spamprob"], axis=1)

In [10]:
df2.tail()

,id,user_id,datestamp,r,g,b,colorname,id,datestamp,language,monitor,temperature,gamma,colorblind,ychrom
3408031,3408033,152401,1.270252e+09,31,79,57,dark teel,152401,1.270252e+09,English,LCD,NaN,NaN,0.0,1.0
3408032,3408034,152401,1.270252e+09,77,0,75,purple,152401,1.270252e+09,English,LCD,NaN,NaN,0.0,1.0
3408033,3408035,152390,1.270252e+09,5,18,55,dark blue,152390,1.270252e+09,Finnish,LCD,NaN,1.0,0.0,1.0
3408034,3408036,152398,1.270252e+09,179,28,183,light purple,152398,1.270252e+09,English,LCD,NaN,NaN,0.0,1.0
3408035,3408037,152393,1.270252e+09,19,14,78,midnight blue,152393,1.270252e+09,English,LCD,NaN,NaN,0.0,1.0

### Ist die Spalte 'colorblind' von Bedeutung?
- Zugriff auf Daten von colorblind mit 1.0

In [11]:
df_colorblind = df2.loc[df2['colorblind'] == 1.0]
# scheinbar können farbenblinde Menschen die Farben doch einordnen, basierend auf dem ersten Eintrag
# r209, g14, b 169 sieht ziemlich purple aus

In [12]:
df_colorblind = df2.loc[df2['colorblind'] == 1.0].sum()
df_colorblind
# Es gibt 126607 Einträge von Menschen, die farbenblind sind
# Das sind 126607/3408036 * 100% = 3.7 % aller Teilnehmer (3408035 Einträge)

id                                                  215960006399
user_id                                               9762056645
datestamp                                              1.606e+14
r                                                       16102880
g                                                       16122891
b                                                       16134408
colorname      purplebluetanyellowgreendark greenblueredpinkg...
id                                                    9762056645
datestamp                                              1.606e+14
monitor        LCDLCDLCDLCDLCDLCDLCDLCDLCDLCDLCDLCDLCDLCDLCDL...
temperature                                          1.87045e+08
gamma                                                  2.574e+50
colorblind                                                126607
ychrom                                                    109719
dtype: object

In [13]:
# Droppen aller Zeilen, die colorblind = 1.0 haben, um RGB-Farbbegriff-Karte ohne Daten der farbenblinden Menschen 
# zu erstellen
df3 = df2[df2.colorblind != 1.0]
df3.loc[df3['colorblind'] == 1.0].sum()
# keine Einträge mehr mit colorblind = 1.0

id             0.0
user_id        0.0
datestamp      0.0
r              0.0
g              0.0
b              0.0
colorname      0.0
id             0.0
datestamp      0.0
language       0.0
monitor        0.0
temperature    0.0
gamma          0.0
colorblind     0.0
ychrom         0.0
dtype: float64

In [14]:
# Droppen der Spalte colorblind
df4 = df3.drop('colorblind', axis=1)
df4.head()

,id,user_id,datestamp,r,g,b,colorname,id,datestamp,language,monitor,temperature,gamma,ychrom
0,1,1,1.267419e+09,72,100,175,pastel blue,1,1.267419e+09,None,LCD,6500.0,2.2,1.0
1,2,1,1.267419e+09,204,177,246,faint violet,1,1.267419e+09,None,LCD,6500.0,2.2,1.0
2,3,1,1.267419e+09,182,226,245,baby blue,1,1.267419e+09,None,LCD,6500.0,2.2,1.0
3,4,1,1.267419e+09,130,64,234,purple,1,1.267419e+09,None,LCD,6500.0,2.2,1.0
4,5,2,1.267419e+09,75,49,234,blue,2,1.267419e+09,None,LCD,6500.0,NaN,1.0

### Herausfinden, ab welcher Häufigkeit noch "sinnvolle" Namen für Farben auftauchen.
- Für jede dieser Farben dann einen Farbraum für r, g und b angeben
- wie kann ich für jeden colorname mir alle dazugehörigen r-, g- und b-Werte ausgeben?
- Für jeden Eintrag in Spalte colorname in colors soll df4 durchsucht werden und jede dazugehörige r,g,b Werte soll in ein neues df geschrieben werden, damit min- und max-Werte von jeder Farbe ausgelesen werden können.
- hierdurch können alle Farben zu einem Farbeintrag dargestellt werden. Wäre der Mittelwert jedes Wert dann die mittlere Farbe?

In [15]:
# Auswahl eines Treshholds, um sinnlose Farbnamen auszuschließen. Treshold = Häufigkeit einer Farbe.
# mit diesem Treshold (4554) habe ich 76 verschiedene Farben
colors = pd.read_sql_query(
    'SELECT ' +
        'colorname, ' +
        'COUNT(*) AS number_entries ' +
    'FROM answers ' +
    'WHERE colorname LIKE "%%" ' +
    'GROUP BY colorname ' +
    'HAVING number_entries > 4554 ' +
    'ORDER BY number_entries Asc; '
    , conn)
colors.tail(100)

        colorname  number_entries
0      chartreuse            4619
1        burgundy            4835
2           khaki            4911
3       brick red            4975
4     kelly green            5045
5       dark teal            5083
6      blue green            5106
7   seafoam green            5398
8    royal purple            5463
9      blue-green            5523
10           plum            5948
11           gold            6265
12      baby blue            6434
13     mint green            6583
14       dark red            6617
15   yellow green            6813
16   yellow-green            6883
17  bright purple            6999
18      pale blue            7049
19           navy            7211
20   burnt orange            7253
21    grass green            7287
22     aquamarine            7774
23     light pink            8170
24     neon green            8222
25    bright blue            8458
26        mustard            8733
27           rose            8810
28         indigo           10674
29     periwinkle           11131
..            ...             ...
46    dark purple           16874
47          olive           17552
48           gray           18237
49   bright green           18827
50          mauve           19147
51   forest green           19356
52           aqua           23316
53      dark blue           23439
54     dark green           23931
55            tan           23976
56           cyan           24735
57       lavender           25794
58      turquoise           26292
59   light purple           29646
60     lime green           31313
61         violet           32801
62       sky blue           34501
63           grey           36125
64        magenta           43720
65         yellow           44068
66    light green           49757
67         orange           52193
68           teal           57123
69     light blue           58119
70            red           69922
71          brown           75798
72           pink          130998
73         purple          249182
74           blue          287938
75          green          314145

[76 rows x 2 columns]

In [16]:
colorlist = list(map(lambda x:f'"{x}"', colors["colorname"].tolist()))
colorlist

['"chartreuse"',
 '"burgundy"',
 '"khaki"',
 '"brick red"',
 '"kelly green"',
 '"dark teal"',
 '"blue green"',
 '"seafoam green"',
 '"royal purple"',
 '"blue-green"',
 '"plum"',
 '"gold"',
 '"baby blue"',
 '"mint green"',
 '"dark red"',
 '"yellow green"',
 '"yellow-green"',
 '"bright purple"',
 '"pale blue"',
 '"navy"',
 '"burnt orange"',
 '"grass green"',
 '"aquamarine"',
 '"light pink"',
 '"neon green"',
 '"bright blue"',
 '"mustard"',
 '"rose"',
 '"indigo"',
 '"periwinkle"',
 '"lime"',
 '"sea green"',
 '"dark pink"',
 '"peach"',
 '"light brown"',
 '"olive green"',
 '"fuschia"',
 '"pale green"',
 '"navy blue"',
 '"hot pink"',
 '"beige"',
 '"black"',
 '"salmon"',
 '"royal blue"',
 '"lilac"',
 '"maroon"',
 '"dark purple"',
 '"olive"',
 '"gray"',
 '"bright green"',
 '"mauve"',
 '"forest green"',
 '"aqua"',
 '"dark blue"',
 '"dark green"',
 '"tan"',
 '"cyan"',
 '"lavender"',
 '"turquoise"',
 '"light purple"',
 '"lime green"',
 '"violet"',
 '"sky blue"',
 '"grey"',
 '"magenta"',
 '"yellow"',
 '"light green"',
 '"orange"',
 '"teal"',
 '"light blue"',
 '"red"',
 '"brown"',
 '"pink"',
 '"purple"',
 '"blue"',
 '"green"']

In [17]:
sql = ('SELECT ' +
'colorname,r,g,b ' +
    'FROM answers ' +
    'WHERE colorname IN (%s) ' +
    'ORDER BY colorname Asc; ') % (','.join(list(colorlist)))
sql

'SELECT colorname,r,g,b FROM answers WHERE colorname IN ("chartreuse","burgundy","khaki","brick red","kelly green","dark teal","blue green","seafoam green","royal purple","blue-green","plum","gold","baby blue","mint green","dark red","yellow green","yellow-green","bright purple","pale blue","navy","burnt orange","grass green","aquamarine","light pink","neon green","bright blue","mustard","rose","indigo","periwinkle","lime","sea green","dark pink","peach","light brown","olive green","fuschia","pale green","navy blue","hot pink","beige","black","salmon","royal blue","lilac","maroon","dark purple","olive","gray","bright green","mauve","forest green","aqua","dark blue","dark green","tan","cyan","lavender","turquoise","light purple","lime green","violet","sky blue","grey","magenta","yellow","light green","orange","teal","light blue","red","brown","pink","purple","blue","green") ORDER BY colorname Asc; '

In [18]:
colors_rgb = pd.read_sql_query(sql, conn)
colors_rgb.head()

  colorname   r    g    b
0      aqua  36  219  173
1      aqua  96  234  180
2      aqua  41  237  155
3      aqua   8  115  107
4      aqua  53  225  199

# Nach Teambesprechung
## folgende Aufgaben:
- correct misspelling and data clean up (drop colorblind, drop single letter colors, no entries etc.)
- collect range of rgb-values for certain colornames like "your mom"
- cluster RGB-values
- t-SNE visualization of the data
- Models: Neural network, deep convolutional network, logReg, KNN etc.
- ensemble voting
- Train, Validate, Test = 0.6, 0.2, 0.2

### Cleaning up data
- drop colorblind --> df4 ist ohne colorblind
- drop rows which colorname is shorter than three letters or has no entry

In [19]:
df4.head()

,id,user_id,datestamp,r,g,b,colorname,id,datestamp,language,monitor,temperature,gamma,ychrom
0,1,1,1.267419e+09,72,100,175,pastel blue,1,1.267419e+09,None,LCD,6500.0,2.2,1.0
1,2,1,1.267419e+09,204,177,246,faint violet,1,1.267419e+09,None,LCD,6500.0,2.2,1.0
2,3,1,1.267419e+09,182,226,245,baby blue,1,1.267419e+09,None,LCD,6500.0,2.2,1.0
3,4,1,1.267419e+09,130,64,234,purple,1,1.267419e+09,None,LCD,6500.0,2.2,1.0
4,5,2,1.267419e+09,75,49,234,blue,2,1.267419e+09,None,LCD,6500.0,NaN,1.0

In [20]:
df5 = df4[df4.colorname != '']

In [21]:
# DataFrame5 enthält keine rows mit mehr leeren Angaben in 'colorname'
df_empty = df5.loc[df5['colorname'] == ""]
df_empty

Empty DataFrame
Columns: [id, user_id, datestamp, r, g, b, colorname, id, datestamp, language, monitor, temperature, gamma, ychrom]
Index: []

#### Entfernen aller Einträge in 'colornames' deren Länge kürzer als 2 Buchstaben ist

In [22]:
long_cnames_idx = list(np.where(df5[['colorname']].applymap(lambda x: len(x)>2))[0]) # indices (not index labels!!!) where colorname is long enough
len(long_cnames_idx)

3256551

In [23]:
df6 = df5.iloc[long_cnames_idx]

# Implementierung von Hunspell, Autocorrector, um falsche geschriebene Einträge zu korrigieren
- eventuell eine Liste von falsch geschriebenen Wörtern angeben lassen und diese dann manuell korrigieren:
    -https://brandonrozek.com/2018/01/identifying-misspelled-words-dataset-hunspell/

In [24]:
# Manuell konnte Hunspell nicht installieren. Suche nach einer Alternative, um Spellchecker zu implementieren
#import hunspell
#spellchecker = hunspell.HunSpell('~/Library/Spelling/en_US.dic',
                                 '~/Library/Spelling/en_US.aff')

ModuleNotFoundError: No module named 'hunspell'

## Spellchecker Ansatz
- Colornames in eine Liste extrahieren
- Wörter in Liste überprüfen lassen, ob diese richtig geschrieben sind
- falsch geschriebenen Wörter durch richtig geschriebene Wörter ersetzen

In [27]:
import newspaper
from lntk import word_tokenize
import enchant
import re

# --> Kann nicht die benötigten Packete via pip oder homebrew installieren

ModuleNotFoundError: No module named 'enchant'

# Clustern der Farben mit unterschiedlichen Algorithmen
- Anzahl der Cluster enspricht Anzahl der Farben

In [33]:
from sklearn.cluster import KMeans

In [47]:
df6.head(1)

,id,user_id,datestamp,r,g,b,colorname,id,datestamp,language,monitor,temperature,gamma,ychrom
0,1,1,1.267419e+09,72,100,175,pastel blue,1,1.267419e+09,None,LCD,6500.0,2.2,1.0

In [49]:
df7 = df6[['r','g','b']]
df7.head(1)

    r    g    b
0  72  100  175

In [51]:
colorcluster = KMeans(n_clusters=11, n_init=10, random_state=42, n_jobs=-1)

In [52]:
colorcluster.fit(df7)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=11, n_init=10, n_jobs=-1, precompute_distances='auto',
    random_state=42, tol=0.0001, verbose=0)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=11, n_init=10, n_jobs=-1, precompute_distances='auto',
    random_state=42, tol=0.0001, verbose=0)

In [55]:
import hunspell

ModuleNotFoundError: No module named 'hunspell'